# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
cache: packages
warnings_are_errors: false
#r_binary_packages: [data.table,jsonlite,rmarkdown]

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
 provider: script
 script: Rscript -e 'pkgdown::deploy_site_github()'
 skip_cleanup: true
 on:
    condition: "$TRAVIS_R_VERSION_STRING = release"

